In [1]:
import pandas as pd, datetime, glob, os

In [2]:
import ipywidgets as widgets
from IPython.display import display, clear_output

Fon dağılımlarını yükleme

In [6]:
csv_files = sorted(glob.glob(os.path.join("tefas2/dagilim", "*.csv")))
dag_dfs = {os.path.basename(f).split('.')[0]: pd.read_csv(f).fillna(0) for f in csv_files}
dates = [pd.to_datetime(key, format='%Y%m%d') for key in dag_dfs.keys()]
assets = list(dag_dfs[list(dag_dfs.keys())[0]].iloc[0].index)[3:]

IndexError: list index out of range

In [4]:
#for element in assets:
#    print(element[:-4])

fon verilerini indirme

In [4]:
newdfs = {}
csv_files = sorted(glob.glob(os.path.join("tefas2/fonlar", "*.csv")))
fon_dfs = {os.path.basename(f).split('.')[0]: pd.read_csv(f).fillna(0) for f in csv_files}
columns_to_float = ['Fiyat','Tedavüldeki Pay Sayısı']
if len(fon_dfs.items()) != len(dag_dfs.items()):
    print('Fon dağılımları ve fiyat verileri dosyaları aynı sayıda değil!')
else: 
    for key, df in fon_dfs.items():
        newdf = df.merge(dag_dfs[key], on='Fon Kodu', how='left', suffixes=('', '_drop'))
        newdf = newdf.drop(columns=[col for col in newdf.columns if col.endswith('_drop')])
        newdf[columns_to_float+assets] = (newdf[columns_to_float+assets]
                                    .replace(r"\.", "", regex=True)
                                    .replace(",", ".", regex=True)
                                    .astype(float))
        #tefas_aum.append(newdf[columns_to_float+[myasset]].prod(axis=1).sum()/100)
        newdfs[key] = newdf

In [5]:
csv_files = sorted(glob.glob(os.path.join("befas/dagilim", "*.csv")))
bdag_dfs = {os.path.basename(f).split('.')[0]: pd.read_csv(f).fillna(0) for f in csv_files}
bnewdfs = {}
csv_files = sorted(glob.glob(os.path.join("befas/fonlar", "*.csv")))
bfon_dfs = {os.path.basename(f).split('.')[0]: pd.read_csv(f).fillna(0) for f in csv_files}
if len(bfon_dfs.items()) != len(bdag_dfs.items()):
    print('Fon dağılımları ve fiyat verileri dosyaları aynı sayıda değil!')
else: 
    for key, df in bfon_dfs.items():
        newdf = df.merge(bdag_dfs[key], on='Fon Kodu', how='left', suffixes=('', '_drop'))
        newdf = newdf.drop(columns=[col for col in newdf.columns if col.endswith('_drop')])
        newdf[columns_to_float+assets] = (newdf[columns_to_float+assets]
                                    .replace(r"\.", "", regex=True)
                                    .replace(",", ".", regex=True)
                                    .astype(float))
        #befas_aum.append(newdf[columns_to_float+[myasset]].prod(axis=1).sum()/100)
        bnewdfs[key] = newdf

NameError: name 'assets' is not defined

In [19]:
bnewdfs['20250207']

,Tarih,Fon Kodu,Fon Adı,Fiyat,Tedavüldeki Pay Sayısı,Hisse Senedi (%),Devlet Tahvili (%),Hazine Bonosu (%),Döviz Kamu İç Borçlanma Araçları (%),Finansman Bonosu (%),...,Yabancı Kamu Borçlanma Araçları (%),Yabancı Özel Sektör B.A. (%),Yabancı Hisse Senedi (%),Yabancı Borsa Yatırım Fonları (%),Yatırım Fonları Katılma Payları (%),BYF Katılma Payları (%),Gayrimenkul Yatırım Fon Katılma Payları (%),Girişim S. Yatırım Fon Katılma Payları (%),Vadeli İşlemler Nakit Teminatları (%),Diğer (%)
0,07.02.2025,AAJ,AGESA HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EME...,0.07,"44,934,165,347.31",24.40,54.30,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,1.93,0.00,3.94,9.45,0.00,0.00
1,07.02.2025,ABE,ANADOLU HAYAT EMEKLİLİK A.Ş.S&P 500 YABANCI BY...,0.28,"28,710,821,024.71",5.68,0.00,0.00,0.00,0.00,...,0.00,0.00,1.07,80.34,0.97,0.00,1.68,1.38,2.89,0.00
2,07.02.2025,ACV,ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATI...,0.05,"9,245,283,125.35",0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9.67
3,07.02.2025,AEA,ANADOLU HAYAT EMEKLİLİK A.Ş. ALTIN KATILIM EME...,0.35,"123,162,675,481.29",0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.05,0.19,0.00,0.00,0.00,0.00
4,07.02.2025,AEB,AGESA HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ GRU...,1.35,"1,892,735,339.67",93.42,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,1.43,0.00,0.00,1.41,2.21,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,07.02.2025,ZHB,TÜRKİYE HAYAT VE EMEKLİLİK A.Ş. SÜRDÜRÜLEBİLİR...,0.24,"16,765,935,228.90",82.16,0.00,0.00,0.00,0.00,...,0.00,0.00,8.74,0.00,0.11,0.00,3.14,6.59,1.01,0.00
378,07.02.2025,ZHD,TÜRKİYE HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ KİRA ...,0.28,"6,109,671,557.85",0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.30
379,07.02.2025,ZHE,TÜRKİYE HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞK...,0.15,"52,415,751,520.29",39.96,10.75,0.00,0.00,0.58,...,0.00,0.00,0.01,0.00,9.14,28.25,0.40,3.81,0.48,0.00
380,07.02.2025,ZHF,TÜRKİYE HAYAT VE EMEKLİLİK A.Ş. KATILIM TEMKİN...,0.08,"17,179,982,709.11",8.70,0.00,0.00,0.00,0.37,...,0.00,0.00,0.00,0.00,9.43,3.23,0.00,2.97,0.00,3.47
381,07.02.2025,ZHG,TÜRKİYE HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA...,0.05,"81,815,628,803.05",0.00,92.65,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,1.04,0.00,1.24,3.88,0.00,0.00

In [20]:
def result_creator(assetchoice):
    tefas_aum = [df[columns_to_float+[assetchoice]].prod(axis=1).sum()/100 for key, df in newdfs.items()]
    befas_aum = [df[columns_to_float+[assetchoice]].prod(axis=1).sum()/100 for key, df in bnewdfs.items()]
    resultdf = pd.DataFrame({'Tefas AUM':tefas_aum, 'Befas AUM':befas_aum}, index=dates).fillna(0)
    resultdf['Toplam AUM'] = resultdf['Tefas AUM'] + resultdf['Befas AUM']
    return resultdf

dfs = {}
for asset in assets:
    dfs[asset[:-4]] = result_creator(asset)
dropdown = widgets.Dropdown(
    options=list(dfs.keys()), M # Dropdown options are the keys of the dataframes dictionary
    description='Select Option:',
)
def update_table(change):
    selected_option = change.new  # Get the selected option from the dropdown
    clear_output(wait=True)  # Clear the previous output
    display(dropdown)  # Redisplay the dropdown
    display(dfs[selected_option])

In [21]:
dropdown.observe(update_table, names='value')
pd.options.display.float_format = '{:,.2f}'.format
display(dropdown)

Dropdown(description='Select Option:', index=14, options=('Hisse Senedi', 'Devlet Tahvili', 'Hazine Bonosu', '…

                  Tefas AUM      Befas AUM       Toplam AUM
2025-02-06 4,578,162,641.50 981,155,101.30 5,559,317,742.80
2025-02-07 4,107,281,760.93 696,791,255.62 4,804,073,016.55